### ISSUE TITLE
Ceruleum Tank doesn't show anything when garland tools data source selected

### ISSUE THREAD

**Issue by electr0sheep** [electr0sheep/ItemVendorLocation#36]
18:07:43.775 | ERR Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot convert type 'string' to 'ulong')
 ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot convert type 'string' to 'ulong'
   at CallSite.Target(Closure, CallSite, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at ItemVendorLocation.VendorPlugin.<>c__DisplayClass59_1.<GetVendors>b__1(Partial i) in /work/repo/ItemVendorLocation/Plugin.cs:line 430
   at System.Collections.Generic.List`1.Find(Predicate`1 match)
   at ItemVendorLocation.VendorPlugin.GetVendors(UInt64 itemId) in /work/repo/ItemVendorLocation/Plugin.cs:line 430
   at ItemVendorLocation.VendorPlugin.<>c__DisplayClass61_0.<HandleItem>b__0() in /work/repo/ItemVendorLocation/Plugin.cs:line 492
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
{ } [ Send ]

**Comment by electr0sheep** [comment]
607572276c3b968d1dbaa4ff808ae2d14a95a3d7
